### ISSUE TITLE
Logging support

### ISSUE THREAD

**Issue by techn0mad** [Galvant/InstrumentKit#155]
Hi all:

I have been tasked with adding some logging support for some instrument classes. I find that since most functions are accomplished with properties and their attendant setters and getters, I wonder how I could add logging to a specific instrument's properties and its setters and getters, without adding it to _all_ instruments?

Thank you,

**Comment by scasagrande** [comment]
There are a few ways you could approach this problem. The first would be to use our currently undocumented logging. You can see those implemented here:

https://github.com/Galvant/InstrumentKit/blob/master/instruments/abstract_instruments/comm/abstract_comm.py#L52
https://github.com/Galvant/InstrumentKit/blob/master/instruments/abstract_instruments/comm/abstract_comm.py#L217
https://github.com/Galvant/InstrumentKit/blob/master/instruments/abstract_instruments/comm/abstract_comm.py#L232

To access those, you need to set `Instrument._file.debug = True`.

```python
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> inst._file.debug = True
```

This is the best because it logs at the communication layer so you also see any characters or lines that have been added. All logging information is then sent to the Python standard logger with priority of `DEBUG`.

You could also hack something together in the class you are working with. This is not something I'd ever accept in a PR, but you could define the `sendcmd` and `query` functions in your instrument class, do your logging, and then pass the execution onto the original version of those functions.

```python
def sendcmd(self, cmd):
    # do some logging here
    super(YourClassName, self).sendcmd(cmd)
```
